# Generated by Django 3.0.7 on 2020-06-24 17:25

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
