# Generated by Django 3.0.7 on 2020-07-01 09:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expires',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 1, 9, 31, 38, 457907, tzinfo=utc), validators=[main.validators.validate_manufactured]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured',
            field=models.DateField(blank=True, validators=[main.validators.validate_manufactured]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_set',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.ProductSet'),
        ),
    ]
