# Generated by Django 3.0.7 on 2020-06-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_distributor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
