# Generated by Django 3.0.7 on 2020-06-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200622_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='password',
        ),
    ]
