# Generated by Django 3.0.7 on 2020-06-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200623_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.Manufacturer', unique=True),
        ),
    ]
