# Generated by Django 3.0.7 on 2020-06-25 13:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200625_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='image',
            field=cloudinary.models.CloudinaryField(default='avatar.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=cloudinary.models.CloudinaryField(default='avatar.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='productset',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
