# Generated by Django 3.0.7 on 2020-06-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200618_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
    ]
