# Generated by Django 3.0.7 on 2020-06-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured',
            field=models.DateTimeField(),
        ),
    ]
