# Generated by Django 3.0.7 on 2020-06-26 06:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200625_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
