# Generated by Django 3.0.7 on 2020-06-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200622_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='manufacturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.Manufacturer'),
        ),
    ]
