# Generated by Django 3.0.7 on 2020-07-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200703_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Farmer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
