# Generated by Django 3.0.7 on 2020-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200625_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='profiles/farmer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(default='avatar.png', upload_to='profiles/manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, upload_to='products/qr_codes'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
