# Generated by Django 3.0.7 on 2020-07-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200705_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.ProductSet'),
        ),
    ]
