# Generated by Django 3.0.7 on 2020-06-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200622_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/qr_codes')),
            ],
        ),
        migrations.RemoveField(
            model_name='productset',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.QrCode'),
        ),
    ]
