# Generated by Django 3.0.7 on 2020-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200621_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured',
            field=models.CharField(max_length=60),
        ),
    ]
