# Generated by Django 3.0.7 on 2020-07-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200705_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='manufacturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='distrib', serialize=False, to='main.Farmer'),
        ),
    ]
