# Generated by Django 3.0.7 on 2020-06-23 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200623_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
