# Generated by Django 3.0.7 on 2020-06-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200621_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured',
            field=models.DateField(),
        ),
    ]
