# Generated by Django 3.0.7 on 2020-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200629_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productset',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
