# Generated by Django 3.0.7 on 2020-06-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200629_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ProductSet'),
        ),
    ]
