# Generated by Django 3.0.7 on 2020-06-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200629_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='product_set',
        ),
    ]
