# Generated by Django 3.0.7 on 2020-06-29 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20200629_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductSet'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
