# Generated by Django 3.0.7 on 2020-06-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200618_1205'),
        ('authentication', '0002_auto_20200618_1428'),
    ]

    operations = [
    ]
